version: '3.7'

volumes:
    logs:
        driver: local

services:
    nginx:
        container_name: slim_nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/www/log/nginx
        depends_on:
            - slim
    slim:
        container_name: slim_php
        build:
            context: docker/php/
            dockerfile: Dockerfile
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www
            - logs:/var/www/logs
#            - docker/php/php.ini:/usr/local/etc/php.ini

    db_local:
        image: mysql:8.0
        container_name: db_local
        environment:
            - MYSQL_ROOT_PASSWORD=admin123
            - MYSQL_DATABASE=Tunaiku_Loan
        volumes:
            - ./mysql:/var/lib/mysql
#        ports:
#            - "3357:3306"